Galooshi/happo

lib/likadan_runner.rb

These floats were pretty long, with way more significant figures than is
actually useful. Rounding it to 1 decimal place cleans up the output a
little.

Round percentages in comparison output to 1 decimal

---

README.md

It isn't obvious that you need to run `likadan review` after the likadan
has finished. Adding this information to the readme will make this tool
much easier for people to pick up.

Add more instructions to the readme

---

lib/views/index.erb

When running likadan locally, I sometimes leave my mouse cursor over the
Firefox window. This sometimes causes a hover style to be activated,
which causes an unnecessary diff. To prevent this from happening, this
commit disables pointer events on everything that is rendered.

Disable pointer events on likadan runner HTML

---

README.md
bin/likadan

@lencioni pointed out [1] that this name was confusing, and better suited
for a feature that would remove any obsolete (old examples no longer
existing) examples.
"clean" is a better name, and is more similar to e.g. `make clean` `ant
clean` etc.
[1]: https://github.com/trotzig/likadan/issues/8

Rename `likadan prune` to `likadan clean`

---

bin/likadan

Running `likadan clean` when the snapshots folder was missing would lead
to an error (something like "No such file or directory"). Since it's
likely that `likadan clean` will be added to scripts, I want it to be
more robust. Adding a guard to make sure that the folder exists will
help.

Fix `likadan clean` for missing snapshots folder

---

lib/likadan_runner.rb
lib/public/likadan-runner.js

We've had issues with js errors making likadan silently fail (a firefox
window opens, then closes - no examples have been run). Adding some code
to record all errors happening and then throwing an error from ruby code
will at least make those errors more visible.
Fixes #18

Surface JavaScript errors that happen during initialization

---

lib/views/index.erb

I was using likadan recently and came across an interesting error:
> Invalid image size, width: 320, height: 0
I have an example that renders a component that happens to take up 0
height. Likadan is just fine with this on the first pass, but on the
second pass when comparing a new version against a baseline, it
blows up with this error.
To prevent this from happening, I am setting a min-height of 1px on the
<body> element. If I understand how this works correctly, this will
cause the snapshot to be at least 1px tall, so it should never store a
0px tall image and run into this problem.
We may want to implement a more thorough fix for this issue at some
point, but this is simple and should at least help people out now.
Fixes #23

Set <body> min-height to 1px on runner document

---

lib/likadan_runner.rb
lib/likadan_uploader.rb

We started seeing the following error when likadan runs in CI:
> You have attempted to create more buckets than allowed
> (S3::Error::TooManyBuckets)
I think we can avoid this by only creating one bucket instead of a new
bucket every time likadan runs. I simply moved the random bucket name to
be a random file name, and created a non-random bucket name.
I decided to switch from SecureRandom.hex to SecureRandom.uuid because
uuid seems more appropriate for this type of thing.
I considered making the filename for the diffs just be the MD5 hash of
the file, which would avoid us from uploading duplicate data if the two
files happened to be the same. However, I didn't think the little bit of
added complexity of finding if the file already exists was worth the
small gain of no duplicates at this …

Avoid creating multiple S3 buckets

---

lib/likadan_runner.rb
lib/views/index.erb
spec/likadan_spec.rb

In 39daf344 I added a min-height to the <body> element to prevent
snapshots from having 0 height when nothing is rendered. I had assumed
this would work, but I assumed incorrectly. This is because likadan
crops the snapshot to fit just the rendered element. To fix this for
real, I am just setting a minimum height and width of 1 on the cropping.
Fixes #23

Prevent one dimensional snapshots

---

lib/likadan_runner.rb
lib/public/likadan-runner.js
spec/likadan_spec.rb

At Brigade We have a likadan for a react component that uses
`requestAnimationFrame` when it renders to set some state. The snapshot
seems to sometimes be taken before this happens, and sometimes after it
happens. It would be nice if there was a way to ensure that the snapshot
is always taken after the `requestAnimationFrame`.
Jasmine solves this by having the function take a callback argument and
requiring the spec to call it when it is done. I think that a similar
technique will work for us here.
I implemented this by making the runner use WebDriver's
`execute_async_script` which injects a callback argument that needs to
be called when the script is done executing. This function can take a
value that gets passed back to Rubyland which we can use in the same way
as before to generate the …

Improve compatibility with things that require asynchronicity

---

lib/likadan_runner.rb
spec/likadan_spec.rb

Previously, a `likadan` run would pass (exit code 0) even if there was
an example that was failing. This led us into accidentally pushing broken
examples to the Brigade codebase. Fixing by failing as soon as a failure
is found will help us prevent pushing bad eggs into the basket.

Fail `likadan` if broken example is found

---

spec/diffux_ci_spec.rb

The `be` matcher compares object identity, which we don't actually care
about here. Switching to `eq` to reduce noise in the test suite.

Use `to eq(...)` instead of `to be(...)`

---

lib/diffux_ci_runner.rb
lib/public/diffux_ci-runner.js
spec/diffux_ci_spec.rb

Instead of iterating blindly until we run out of examples, we now first
get a list of all examples and then use that list to iterate. This will
help an upcoming change to parallellize execution.
Since I changed the array of defined examples into a hash/object, I had
to move the duplicate description introduced in e45442a into javascript
land.

Pass list of examples from JS to Ruby

---

bin/diffux

Instead of just saying "Unknown command: foo" if you execute `diffux_ci
foo`, we now also display the help text that @lencioni added in
73242e64.

Display help text on unknown action

---

README.md
lib/public/diffux_ci-runner.js
spec/diffux_ci_spec.rb

I sometimes want to focus on multiple examples at the same time. Now that we compile a list of descriptions, expanding `fdefine` to allow for multiple examples is fairly trivial. This also matches RSpec and Jasmine behavior, which is more likely what people will expect anyway.

Make `fdefine` work for multiple examples simultaneously

---

README.md
lib/public/diffux_ci-runner.js

There was a soft dependency to React in that you could return a React
component from your examples instead of a DOM node. This dependency was
problematic in that we expected a globally defined `React` variable to
exist. I'm removing this dependency and moving the responsibility to the
examples instead.
To have a way to clean up event listeners and such, I'm adding a
`cleanOutElement` method that you can override. For React, this is where
you should unmount components.
Fixes #47

Remove dependency on React

---

lib/public/diffux_ci-runner.js
lib/views/index.erb

We were previously just removing any visible elements from the body,
which requires a little overhead to determine if the element is visible.
I believe we were doing this to avoid removing our script tags which
were in the body. I think that if we move the script tags to the head,
we can do this more simply.
In my unscientific test, this didn't seem to have much of an impact on
performance, but it is simpler so I think it is still worth doing.

Simplify clearing out document between examples

---

lib/public/diffux_ci-runner.js

I realized that we were filtering the descriptions down to be the same
array as `this.fdefine`, so we can just totally skip that step and just
use `this.fdefine` instead.

Simplify fdefine filtering

---

lib/diffux_ci_runner.rb

Under the hood, this will cause ChunkyPNG to allocate a new array of
pixels for the cropped image, and then slice out the pixels needed for
the cropped image from the uncropped image and put them into the new
array. If we don't actually need to crop, we can avoid this work and
memory allocation.
In the Brigade diffux test suite this seemed to happen a few times, but
not enough to make a noticeable difference in performance. Still, since
it is such an easy thing to do, we might as well do it.

Avoid cropping unless we actually need it

---

lib/public/diffux_ci-runner.js

We call this function asynchronously from Ruby. In order for it to know
what is happening, we need to make sure that doneFunc() is called. Since
we already have a catch block wired up, we can just move our throw into
there and we should be good to go.
I added a comment to help explain this bit of weirdness for the future.
I also decided to throw a new Error object to give us more context here,
like a stack trace, if we end up wanting that.

Make sure renderExample() errors gracefully

---

README.md
lib/diffux_ci_uploader.rb

I came across a bug trying to upload diffs locally. It turns out that
bucket names need to be globally unique (not only unique for an
account). I'm adding a new configuration option to resolve this.
Fixes #60

Make s3 bucket name configurable

---

lib/diffux_ci-diffs.html.erb
lib/diffux_ci_server.rb
lib/diffux_ci_utils.rb
lib/views/review.erb
spec/diffux_ci_spec.rb
spec/diffux_ci_utils_spec.rb

A problem with using the filesystem directly as the storage for
snapshots and diffs is that we've had to escape example descriptions in
order to use them as valid folder names. In #40, @lencioni and I have
discussed using base64 encoding to use as folder names. The upside is
that we can keep the real description throughout the UI (no more
weird underscores on the review screen). The downside is that the
structure is now obfuscated to a certain degree. What would before look
like this
snapshots
|- _Foo_
|- @320
|- baseline.png
|- _Bar_
|- @320
|- baseline.png
|- diff.png
|- candidate.png
Will now look like this
snapshots
|- PEZvbz4NCg==
|- @320
|- baseline.png
|- PEJhcj4NCg==
|- @320
|- baseline.png
|- diff.png
|- candidate.png
This probably doesn't matter, as the folder structure is an …

Use base64 encoding for folder names

---

lib/diffux_ci/public/diffux_ci-runner.js

This change allows the user to better see where the error came from. The
stack trace helps the user to more easily debug the error.

Improve error stack trace

---

README.md
lib/diffux_ci/public/diffux_ci-runner.js
spec/diffux_ci_spec.rb

This is similar to how Mocha works. In Mocha, async tests can either
take a `done` callback or return a `Promise`. This gives us a slightly
nicer API for working with asynchronous examples.
Fixes #77.
cc: @serena-w

Allow for async examples to return Promises

---

lib/diffux_ci/utils.rb
spec/diffux_ci/utils_spec.rb
spec/diffux_ci_spec.rb

It turns out that Base64.encode64 adds newlines after a certain length.
This ends up causing problems when used in filenames. Instead, we can
use Base64.strict_encode64, which does the same thing but without
newlines.
Fixes #76.

Prevent newlines in directory names

---

lib/diffux_ci/server.rb
lib/diffux_ci/utils.rb
spec/diffux_ci_spec.rb

I added a way for diffux to be configured to look for resources in other
directories. This allows the usage of custom fonts and resolves the issue
https://github.com/diffux/diffux_ci/issues/82. I also added a test to
check that diffux can find files in other directories specified in its
config.
fixes #82

Allow additional directories to be specified in the config

---

README.md
lib/happo/uploader.rb

The S3 credentials used for uploading diff images are now required to be
specified by environment variables, instead of in the `.happo.yaml`
file. Users must set `S3_ACCESS_KEY_ID`, `S3_SECRET_ACCESS_KEY`, and
`S3_BUCKET_NAME` as environment variables to use `happo upload_diffs`.
Users can also set `S3_BUCKET_PATH` as an environment variable if they
wish to specify a directory path for where they want diff images
uploaded within the S3 bucket. This also addresses https://github.com/Galooshi/happo/issues/91.

Make S3 credentials be specified by environment variables

---

lib/happo/uploader.rb

Asking for all buckets may lead to access denied errors if the IAM role or user
associated with the provided access key pair does not have permissions for all
buckets. Furthermore, we only need to retrieve the bucket specified by the
environment variable `S3_BUCKET_NAME` to put diff images into, and we should
definitely have access to `S3_BUCKET_NAME` with the provided S3 credentials. Thus, we should use `service.bucket(@s3_bucket_name)` instead of `service.buckets.find(@s3_bucket_name)`.
For some reason, the `service.bucket("bucket_name")` method was not specified
in the README for the `s3` library, and the only example in the documentation
for finding a single bucket was `service.buckets.find("bucket_name")`. I have
submitted a pull request to update the documentation there as well: …

Get single S3 bucket instead of all buckets

---

lib/happo/uploader.rb

In https://github.com/Galooshi/happo/pull/93, we changed from using
`service.buckets.find` in `uploader.rb` to `service.bucket`. However, I
forgot to change the line that used `service.buckets.build`, which
instantiates a new bucket just as `service.bucket` does.
`service.buckets.build` does use a `proxy_owner` argument, which is
actually just `service` since that argument is passed into
`BucketExtensions` as `self` in `service.buckets`
(https://github.com/qoobaa/s3/blob/ec570632d25a3571cd4585de08e48e72b838f048/lib/s3/service.rb#L48).
`service.bucket` also creates a bucket with `self` for the same argument
(https://github.com/qoobaa/s3/blob/ec570632d25a3571cd4585de08e48e72b838f048/lib/s3/service.rb#L55).
Thus, the bucket `service.buckets.build` creates should be identical
to a bucket …

Remove unnecessary line for building S3 buckets

---

lib/happo/server.rb

This commit deals with this issue
https://github.com/Galooshi/happo/issues/95. Now, if you run `happo
debug` and try to go to a file that cannot be found, a 404 error is
raised. Previously, you would have gotten a 202 error if a file could
not be found. I missed this bug in
https://github.com/Galooshi/happo/pull/86.

Show 404 error for file not found

---

lib/happo/uploader.rb

With this change, the image elements in the generated `index.html` for
`happo upload_diffs` will use relative paths instead of absolute paths
for their source urls.
In my case, I'm using a proxy to allow developers without access to the
S3 bucket containing the image and HTML files Happo creates to also see
the visual diffing images. I would like to use the generated
`index.html` to present the visual diffing images, but the browser would
not have the access to get to the absolute paths leading to the S3 bucket for
the images. Using relative paths allows the images to be retrieved using
the proxy as well.

Use relative paths instead of absolute paths for images

---

lib/happo/uploader.rb

In https://github.com/Galooshi/happo/pull/98, I wanted the `index.html`
file generated by `happo upload_diffs` to use relative paths for the
visual diffing screenshots, rather than absolute paths. However, the
images and `index.html` are in the same directory, so I didn't do the
relative paths correctly. The relative paths for the images in
`index.html` are correct now.

Fix uploader to use correct relative paths

---

lib/happo/uploader.rb

Previously, `happo upload_diffs` would throw an error every time
the `previous.png` image for a test could not be found. Thus, if a new
test was defined or if the component didn't change, `happo upload_diffs`
would throw an error. For new images with no `previous.png` or
`diff.png`, the uploader should upload `current.png`.

Fixed uploader bug for new images

---

lib/happo/uploader.rb

An example description may contain unsafe characters like quotation
marks or other punctuation marks that would break the URL used for the
image source in the generated `index.html`. We need to escape unsafe
characters in example descriptions so that the image source URL always
works correctly in the page displaying diff images and new examples.

Escape unsafe characters in example descriptions

---

lib/happo/public/happo-runner.js

There are some times when you have a component that contains an
absolutely positioned element, or something that has styles that break
out of the layout of the container. In this case, I usually end up
adding a wrapper that has a hard-coded height, to ensure that I am able
to include the entire component in the snapshot, including the
absolutely positioned item. This is not ideal because:
1. I have to know about this quality of the component I am testing.
2. I have to figure out the correct height and hard-code it.
3. If the height of the component changes, my screenshot may end up
breaking or being less useful.
4. If the component changes to include something like this after the
fact, screenshots may not catch it.
This commit takes a stab at automating this by recursing through all …

Get coordinates of all descendants

---

lib/happo/public/happo-runner.js
spec/happo_spec.rb

We currently recurse through the DOM tree using
`getBoundingClientRect()` to determine the shape of the box that we want
to take a screenshot of. This is working well, except when the topmost
element has margin on it, since `getBoundingClientRect()` does not
include margin. This means that you might miss some important details
about the visual appearance of your component if you aren't being super
careful.
I think we should use `getComputedStyle()` to determine the margin of
the topmost element and use that in our rectangle dimension
calculations. I want to avoid doing this for every node in the tree,
since it is not very fast. I think doing this on the topmost element
will likely get us 99% of the benefit, so it seems like an easy win.
Fixes #108.
cc: @serena-w

Include margin of topmost element in dimension calculations

---

lib/happo/public/happo-runner.js
spec/happo_spec.rb

In the brigade codebase, we have a component that renders 1px outside
the screen. The recent code we've added to improve the detection of the
box wasn't taking into account that elements might render off-screen.
Adding a simple check to see if either top or left is negative fixes the
issue. I didn't address this for elements that expand right or bottom of
the screen as I think the screenshotting process already handles those
(by including the content).

Fix snapshots that expand the top/left of the screen

---

.rubocop.yml
lib/happo/public/happo-styles.css
lib/happo/server.rb
lib/happo/utils.rb
lib/happo/views/diffs.erb
review-demo.rb

We want to vastly improve the diffs page, but that is slow going because
we don't have a super easy way to preview our changes. This commit fixes
this by adding a review-demo.rb script that starts up a server with some
dummy data in it so we can see what a diffs page might look like. This
should make it easier to improve this page.
Fixes #103

Add way to demo the review page, improve review page

---

lib/happo/views/debug.erb
lib/happo/views/diffs.erb
lib/happo/views/index.erb

We are currently seeing a weird encoding issue on the uploaded diffs
page. I'm not sure if this will resolve that, but it is the right thing
to do and it might help.
Addresses #121

Add meta charset utf-8 to all pages

---

lib/happo/uploader.rb

We are seeing encoding issues on the HTML we upload to S3. Although I am
not able to find any good documentation on this, I believe that we can
set the content-encoding like this.
Relevant source code:
https://github.com/qoobaa/s3/blob/29363972/lib/s3/object.rb#L8
Probably fixes #121

Set content-encoding to utf-8 on uploaded HTML

---

lib/happo/public/HappoDiffs.jsx
lib/happo/public/happo-styles.css

Our first pass at this didn't show the entire image if the previous
image was larger than the current image. I decided to fix this by
taking an alternate approach that uses containers with hidden
overflow. This gives us more control over how these elements behave.
Since this technique uses translateX, which uses percentages based off
the element instead of the container, I needed to switch the cursor
left position from being a percentage to being an absolute number.

Make image swiping work for all image sizes

---

lib/happo/public/happo-runner.js
spec/happo_spec.rb

I have a component that adds its own scrollable container within the
document. This causes the scrollbar to be part of the component, and
therefore, part of the screenshot. For some reason, the scrollbar is
sometimes a slightly different color, which causes a spurious diff.
This is in Travis CI.
I'm not entirely sure why the scrollbar is sometimes different.
Regardless, I don't think it is all that useful to have the scrollbar as
part of the screenshot.
I came up with the idea to check each node and see if it has a scrollbar
by comparing the scroll dimensions to the client dimensions. If it does,
we simply re-style the node to be `overflow: hidden`. In a
proof-of-concept with 10,000 nodes, adding this check to the traversal
and bounding client rectangle check adds essentially no extra …

Disable nested scrollbars before taking screenshots

---

README.md
example-project/example.js
lib/happo/public/happo-runner.js
spec/happo_spec.rb

I've been looking into a case where we get spurious diffs on a scrollbar
added to an element. In 239611300f I added some code that disabled
scrollbars on nested elements, but this didn't work for my particular
case.
After looking at this more closely for this case, I have determined that
this is happening because this component happens to use a portal to
render its contents in a different node. In this case, we are using the
`snapshotEntireScreen` option to take a screenshot of the whole screen.
Not only does this bypass the entire code tree that has the scrollbar
disabling logic in it, it also wouldn't work with that logic because
that only affects nodes within the tree starting with the node returned
by the example--but in this case, all of the DOM nodes are outside of
that tree.
I …

Include all nodes in screenshots

---

lib/happo/public/happo-runner.js
spec/happo_spec.rb

In 5428434cc1f we changed Happo to include all nodes in screenshots.
This means that the async done callback doesn't need to take any
arguments. However, we still had some code here enforcing this.

Allow async done callback to take no arguments

---

lib/happo/public/happo-runner.js
spec/happo_spec.rb

After upgrading to 2.7.3 (from 2.5), we're seeing a bunch of mysterious
diffs coming from the code that is meant to prevent scrollbars.
[Fixes #146]
[Fixes #145]
Instead of applying `overflow: hidden` whenever we notice something
overflowing, we now also check to see that there's an `overflow: auto`
or `overflow: scroll` present. This check is a bit expensive, but if we
can do it only in cases of actual content overflow we're mostly
protected from performance issues.

Improve scrollbar-prevention

---

lib/happo/public/happo-runner.js
spec/happo_spec.rb

Due to how we initialized the box at the top left corner, all snapshots
always started at the top left. This isn't great if you have a component
rendering at the right or bottom edge of the screen.
In the Brigade codebase, we have a <Toast> component that renders at the
bottom of the screen. Before this change, the snapshot would include a
large gray box above the component. After this change, only the
component is included in the snapshot.

Don't assume elements start at top left corner

---

lib/happo/public/happo-runner.js
spec/happo_spec.rb

Some components may have sub-pixel values for their location or
dimensions. Due to the way we were rounding values, this would cause
them to be incorrectly cropped, which made them lose the final row or
column of pixels. I fixed this by rounding top/left down and
right/bottom up before calculating the width and height, which ensures
that we always include the entire component in the screenshot.
Fixes #151

Improve screenshotting of components with sub-pixel dimensions

---

lib/happo/views/index.erb

I am using Happo in a project that uses Aphrodite for styling React
components. Aphrodite works by generating classes with styles that all
have !important on them. This ends up overriding our animation disabling
that we've set up here, since they both use !important and the
specificity on the classes will always be higher than the star selector.
My first attempt at fixing this issue involved adding some JavaScript
that looks through the Aphrodite stylesheet for animations and adding a
rule to the end of it to re-disable the animations. This seemed to work
in debug mode, but it still ended up capturing the animation at a
different frame when running Happo. I tried to work around this by
introducing a delay and forcing a repaint, but no amount of delay seemed
to help.
After a bit of …

Disable animations via animation-play-state

---

lib/happo/public/happo-styles.css

The progress bar that displays during diff computation is designed to be
the width of the image. This is nice because it gives a hint to what
size the resulting diff image is going to be. When the image is wider
than the available screen space however, it gets confusing. I've been
looking at a few (really large) diffs where it looked like progress was
at 100% when it was in fact like 60%. Using a max-width here helps
prevent this.
After being confused that my `calc` was resulting in the wrong value, I
realized that I was in content-box land (oh the horror). So I added a
general rule to move us over to border-box.
I'm starting to feel the pain of:
- not being able to use variables (the 10px must be kept in sync with
other places)
- not having styles better attached to the components
- not …

Prevent <SmoothProgress> from being wider than window

---

packages/happo/src/__tests__/processSerially-test.js
packages/happo/src/cli.js
packages/happo/src/processSerially.js

to: @lencioni @trotzig 
This is required in the CLI, because when you define multiple targets we want them to run serially rather than in parallel, since they will likely use some of the same ports and what not.

Process targets serially to prevent collision

---

packages/happo-target-react-native/src/setupServerAndWaitForSnapshots.js

Fix port number in log message. It was hardcoded to `5000`.
to: @lelandrichardson @lencioni

[target-react-native] Fix port number in log message

---

packages/happo-target-firefox/package.json

Version 3.4.0 is giving us errors:
```
(node:2070) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/home/travis/build/org/project/node_modules/selenium-webdriver/lib/promise.js:2634
throw error;
^
WebDriverError: Unable to parse new session response:
{"sessionId":"c22dff5b-04a4-41a1-804a-59b106ca81ec","value":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"52.0.1","moz:accessibilityChecks":false,"moz:processID":2096,"moz:profile":"/tmp/rust_mozprofile.6Kn1fST0TASk","pageLoadStrategy":"normal","platformName":"linux","platformVersion":"3.13.0-105-generic","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"page …
```

Pin selenium-webdriver at 3.3.0

---

packages/happo-target-firefox/src/waitForImagesToRender.js

Took me some time to figure out where the error was coming from. That should help.
> Failed to load image with url data:image/svg+xml;utf8,<svg%20viewBox=\'0%200%2010%2011\'%20xmlns=\'http://www.w3.org/2000/svg\'><g%20stroke=\'%23bfc7d8\'%20stroke-width=\'1.5\'%20fill=\'none\'%20fill-rule=\'evenodd\'%20stroke-linecap=\'round\'><path%20d=\'M5%201.5v8M9%205.5H1\'/></g></svg>
Also linked to #207.

Improve error reporting

---

.travis.yml
package.json
packages/happo-target-firefox/src/__tests__/findBackgroundImageUrls-test.js
packages/happo-target-firefox/src/__tests__/waitForImagesToRender-test.js
packages/happo-target-firefox/src/findBackgroundImageUrls.js
packages/happo-target-firefox/src/waitForImagesToRender.js

Closes #207.
Come into that issue trying to add happo to the [storybook](https://github.com/storybooks/storybook) of [react-instantsearch](https://github.com/algolia/react-instantsearch).

fix(firefox): handle data uris

---

packages/happo-viewer/package.json

worker-loader pre-1.0.0 has a peerDependency that does not allow webpack
3. This prevents projects that want to update to webpack 3 from getting
onto that version.
The only breaking change listed here is about loader-utils, which I
don't think will impact this project.
https://github.com/webpack-contrib/worker-loader/releases/tag/v1.0.0

[happo-viewer] Bump worker-loader ^0.7.1 -> ^1.0.0

---

packages/happo-target-firefox/src/__tests__/fixtures/srcsetExample.js
packages/happo-target-firefox/src/__tests__/runVisualDiffs-test.js
packages/happo-target-firefox/src/waitForImagesToRender.js

This commit is a port of changes I've made to the new runner for
happo.io. By waiting for images in srcset attributes, we can prevent
spurious diffs.
Instead of trying to figure out which one of the images will be
displayed in the current viewport, I decided to download all. The
tradeoff here being simplicity over performance (dowloading only one of
the images would be faster).
While running tests locally, I noticed that I was getting 2x images
compared to what's in CI. I decided to make the assertions a little
looser to account for both 1x and 2x screenshots.

Wait for images defined in srcset attributes

---

packages/happo-target-firefox/src/__tests__/getUrlsFromSrcset-test.js
packages/happo-target-firefox/src/getUrlsFromSrcset.js
packages/happo-target-firefox/src/waitForImagesToRender.js

My first attempt at this (312ecd9) was too naive, it didn't take urls
with commas in them into account. In this second attempt, I've tried to
tdd things so that I know we can handle a wider range of values.
I've used https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
as a guide into figuring out possible values.

Fix grabbing urls from srcset attributes

---

packages/happo-target-firefox/package.json
packages/happo-target-firefox/src/getUrlsFromSrcset.js

As pointed out by @ljharb in a previous PR: https://github.com/Galooshi/happo/pull/224#pullrequestreview-127401748
Multiple benefits here:
- we avoid the while-loop
- no mutation of the lastIndex property of the regexp

Use string.prototype.matchall to grab urls from srcset

---

packages/happo-target-firefox/package.json
packages/happo-target-firefox/src/__tests__/fixtures/crossOriginImageExample.js
packages/happo-target-firefox/src/__tests__/fixtures/crossOriginImageExamples.js
packages/happo-target-firefox/src/__tests__/runVisualDiffs-test.js
packages/happo-target-firefox/src/__tests__/waitForImagesToRender-test.js
packages/happo-target-firefox/src/waitForImagesToRender.js

I've had spurious diffs reported from images with a crossorigin
attribute. This could be because the browser kicks off different
requests for the crossorigin image and the preloaded image. This creates
a race condition: if the crossorigin image isn't ready by the time the
preload image is downloaded, it won't show up in the screenshot. We can
fix this by transferring crossorigin information from the original image
to the temporary Image created as part of preloading.

Wait for images with crossorigin=anonymous

---

packages/happo-target-firefox/src/HappoRunner.js

Instead of hard-coding it to 3 seconds

Allow the async timeout duration to be configured per-example

---

packages/happo-target-firefox/package.json
packages/happo-target-firefox/src/__tests__/getUrlsFromSrcset-test.js
packages/happo-target-firefox/src/__tests__/runVisualDiffs-test.js
packages/happo-target-firefox/src/getUrlsFromSrcset.js

We found a bug where srcsets with multiple URLs and mixed descriptors
would be parsed incorrectly, causing the first URL without a descriptor
to include a trailing comma. Instead of relying on this regex, I found
what appears to be a good package for parsing this string according to
the spec.
@trotzig @ljharb @sharmilajesupaul

Replace srcset parsing regex with parse-srcset package
